---
name: Spotify Connect
version: dev
slug: spotify
description: Play Spotify music on your Home Assistant device
url: https://github.com/DarkMatterMatt/addon-spotify-connect
arch:
  - aarch64
  - amd64
  - armv7
host_network: true
audio: true
init: false
options:
  name: Home Assistant
  bitrate: 160
  initial_volume: 100
  volume_scaling: log
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  name: str
  bitrate: list(96|160|320)
  initial_volume: int(0,100)
  volume_scaling: list(linear|log|fixed)
  username: str?
  password: password?
  autoplay: bool?
  initial_volume: int(0,100)?
  enable_volume_normalisation: bool?
  librespot_options: str?
